export type Project = {
  id: number;
  name: string;
  collabs: string[];
  type: string;
  date: string;
  hidePreview?: boolean;
  featured?: boolean;
  description?: string;
  content?: string;
  contentSections?: {
    title: string;
    items: string[];
  }[];
  links?: {
    github?: string;
    demo?: string;
    docs?: string;
  };
  technologies?: string[];
  images?: {
    src: string;
    alt: string;
  }[];
  features?: {
    title: string;
    description: string;
  }[];
  workflow?: string[];
};

export const projects: Project[] = [
  {
    id: 4,
    name: "llm stock trader, fine-tuning & rl alignment",
    date: "april, 2026",
    collabs: [],
    type: "ml/fine-tuning",
    featured: true,
    description:
      "15 fine-tuning experiments (sft to grpo) on deepseek 7b with lora r=16. score improved from 0.300 to 0.537 (+79%). diagnosed 3 training failures: hold collapse, reward hacking, kl catastrophe.",
    contentSections: [
      {
        title: "training journey",
        items: [
          "15 fine-tuning experiments (sft -> grpo) on deepseek 7b with lora r=16 (q/k/v/o), lr=5e-6",
          "score: 0.300 (base) -> 0.417 (sft) -> 0.537 (grpo), +79% total improvement",
          "sft trained on 12k reverse-distilled dataset, outperformed larger noisy sets",
          "grpo trained against a 1.22m-param causal transformer world model as synthetic environment",
        ],
      },
      {
        title: "training failures diagnosed",
        items: [
          "hold collapse: agent learned inaction is never penalized, 85% hold actions. fixed with data rebalancing",
          "reward hacking: 84% of reward came from formatting, not trading quality. fixed with asymmetric reward decomposition",
          "kl catastrophe: kl divergence hit 4.2, destroyed base model knowledge, score dropped to 0.301. fixed with kl coefficient tuning",
        ],
      },
      {
        title: "dataset engineering",
        items: [
          "12k reverse-distilled sft dataset from gpt-4 rollouts through the trading environment",
          "outperformed larger noisy datasets — quality over quantity for domain-specific fine-tuning",
          "asymmetric reward decomposition separates format compliance from trading quality to prevent spec gaming",
        ],
      },
    ],
    links: {
      github: "https://github.com/sarthakbiswas97/stock-trader-env",
      docs: "https://huggingface.co/sarthakbiswas/stock-trader-grpo-neural-model",
    },
    technologies: [
      "deepseek 7b",
      "unsloth",
      "lora",
      "trl",
      "grpo",
      "pytorch",
      "hugging face",
    ],
    features: [
      {
        title: "sft -> grpo pipeline",
        description:
          "two-stage training: supervised fine-tuning on distilled demonstrations, then grpo reinforcement learning against a neural world model. each stage addresses different failure modes.",
      },
      {
        title: "specification gaming diagnosis",
        description:
          "documented 3 distinct training failures (hold collapse, reward hacking, kl catastrophe) with root cause analysis and fixes. each failure taught a lesson about reward design and training dynamics.",
      },
      {
        title: "reverse distillation",
        description:
          "12k training examples generated by running gpt-4 through the trading environment and filtering for high-scoring trajectories. smaller, cleaner dataset outperformed larger noisy alternatives.",
      },
      {
        title: "asymmetric reward decomposition",
        description:
          "separates format compliance reward from trading quality reward. prevents the model from gaming the reward by producing well-formatted but poor trading decisions.",
      },
    ],
    workflow: [
      "generate training data by running gpt-4 through the stock trading environment",
      "filter and curate 12k high-quality demonstrations for sft",
      "train sft checkpoint with lora r=16 on deepseek 7b (q/k/v/o targets)",
      "train grpo on top of sft checkpoint using neural world model as environment",
      "evaluate on held-out market episodes, diagnose failures, iterate on reward design",
    ],
  },
  {
    id: 1,
    name: "stock trader rl environment",
    date: "april, 2026",
    collabs: [],
    type: "rl/ml",
    featured: true,
    description:
      "openenv-compliant reinforcement learning environment for evaluating llm trading agents on indian equity markets. meta pytorch openenv hackathon finalist (top 800 out of 32,000+ teams).",
    contentSections: [
      {
        title: "what it does",
        items: [
          "simulates daily stock trading on nifty stocks using ~5 years of real historical ohlcv data",
          "agents connect via http/websocket, receive market observations with technical indicators, and respond with plain-text trade actions (buy, sell, hold)",
          "three difficulty tiers: single stock (20 days), portfolio (30 days), full autonomous (40 days) with escalating constraints like transaction costs, slippage, position limits, and regime gates",
        ],
      },
      {
        title: "how it works",
        items: [
          "market simulator replays historical price windows with a 50-day lookback buffer for indicator computation",
          "feature engine computes rsi, macd, bollinger bands, volume spikes, trend, momentum, and volatility — served as human-readable text summaries for llm agents",
          "step-level reward shaping: pnl reward, discipline bonus, regime gate penalty, trade limit violations",
          "task-specific graders score the full trajectory on sharpe ratio, discipline, regime compliance, and risk management",
        ],
      },
      {
        title: "world model",
        items: [
          "1.22m-param causal transformer world model (mdn output with 3 gaussians) as synthetic training environment for grpo",
          "volatility 0.94x reality, mae 0.0167 — generates realistic market episodes without replaying historical data",
          "drop-in replacement for static csv replay, enabling unlimited training rollouts",
        ],
      },
      {
        title: "why it matters — rlvr & grpo",
        items: [
          "the grading system is designed as a verifiable reward function (rlvr) — deterministic scores that replace traditional reward models",
          "this enables grpo-based training: generate multiple rollouts through the environment, rank them by grader score, and update model weights to favor better trading trajectories",
          "no separate reward model or critic needed — the environment's graders are the reward signal",
        ],
      },
    ],
    links: {
      github: "https://github.com/sarthakbiswas97/stock-trader-env",
      demo: "https://huggingface.co/spaces/sarthakbiswas/stock-trader-env",
    },
    technologies: [
      "python",
      "fastapi",
      "pydantic",
      "docker",
      "websocket",
      "openenv",
      "hugging face spaces",
    ],
    features: [
      {
        title: "meta pytorch hackathon finalist",
        description:
          "qualified for the finale (top 800 out of 32,000+ teams). presented the environment to meta engineers in bangalore, april 2026.",
      },
      {
        title: "three difficulty tiers",
        description:
          "single stock (easy, 20 days), portfolio (medium, 30 days), and full autonomous (hard, 40 days) with escalating constraints — transaction costs, slippage, position limits, trade caps, and regime gates.",
      },
      {
        title: "1.22m-param causal transformer world model",
        description:
          "mdn output with 3 gaussians generates synthetic market episodes. volatility 0.94x reality, mae 0.0167. drop-in replacement for csv replay, enabling unlimited grpo training rollouts.",
      },
      {
        title: "verifiable reward design (rlvr)",
        description:
          "deterministic grading functions that score agents on sharpe ratio, discipline, regime compliance, and risk management. designed to serve as verifiable rewards for grpo-based rl training — no separate reward model needed.",
      },
      {
        title: "llm-native interface",
        description:
          "plain-text action space (buy, sell, hold) and human-readable market summaries — any llm can act as an agent without special tooling. invalid actions gracefully default to hold.",
      },
      {
        title: "seed-reproducible episodes",
        description:
          "fully deterministic episodes for reproducible evaluation. same seed produces same market window and sequence.",
      },
    ],
    workflow: [
      "agent connects via http/websocket and resets environment with a task and seed",
      "environment selects a random market window and returns initial observation",
      "agent reads market summary with technical indicators and submits trade action",
      "environment executes trade with realistic costs/slippage, computes reward, advances to next day",
      "at episode end, grader scores the full trajectory on task-specific criteria",
    ],
  },
  {
    id: 2,
    name: "eta prediction engine",
    date: "may, 2026",
    collabs: [],
    type: "ml/deep learning",
    featured: true,
    description:
      "3-model ensemble (neural net + lightgbm + ft-transformer) for eta prediction. trained on 37m trips, achieves 253s mae — 28% better than xgboost baseline, inference under 4ms on cpu.",
    contentSections: [
      {
        title: "what it does",
        items: [
          "predicts taxi trip duration given pickup zone, dropoff zone, timestamp, and passenger count using 37 million real yellow taxi trips from 2023",
          "learns all spatial relationships from trip data via zone embeddings — no external geography, shapefiles, or hardcoded coordinates. if zone ids mapped to a different city, the model would work equally well",
          "serves predictions in under 4ms on cpu with a 3-model ensemble, packaged in a ~500mb docker container",
        ],
      },
      {
        title: "the ensemble",
        items: [
          "model 1: dual-branch embedding network (560k params) — zone embeddings with hash-based pair embedding, 24 continuous features, residual blocks. best at smooth interpolation for common routes",
          "model 2: lightgbm (81 trees) — gradient-boosted trees with zone ids as native categoricals. near-zero bias (-6s) on rare pairs where the neural net struggles (-106s bias)",
          "model 3: ft-transformer (406k params) — implemented from scratch, each feature projected into a 128-dim token, 3-layer self-attention with [cls] aggregation. positive bias (+65s) offsets nn's negative bias",
          "ensemble weights optimized via grid search on full dev set: 0.6 nn + 0.2 lgbm + 0.2 ft-transformer",
        ],
      },
      {
        title: "feature engineering",
        items: [
          "14 zone-pair statistics with bayesian shrinkage — smooths sparse pairs toward pickup-zone mean with a fallback hierarchy: pair -> pickup zone -> dropoff zone -> global mean",
          "6 traffic-regime time buckets (late night, early morning, am rush, midday, pm rush, evening) with per-regime pair statistics",
          "10 temporal features: cyclical hour/dow/month encoding, rush hour flags, night flags, normalized minute-of-day",
          "zone-pair median alone (296.7s) beats xgboost (351s) with zero ml — the signal is in the feature engineering",
        ],
      },
      {
        title: "results",
        items: [
          "253s mae — 28% better than xgboost baseline (351s). ensemble reduced mae from 261s (best single model) to 253s",
          "nn: 261.2s (precision on common routes) | lgbm: 261.7s (low bias on rare pairs) | ft: 284.7s (different error pattern, bias offset)",
          "diagnostic-driven tuning identified rare-pair bias as the true bottleneck — no amount of nn tuning could fix it, lightgbm solved it",
          "inference under 4ms per request via onnx runtime, total model weights 6.3mb (2.3 + 2.4 + 1.6)",
        ],
      },
    ],
    links: {
      github: "https://github.com/sarthakbiswas97/eta-engine",
      docs: "https://huggingface.co/sarthakbiswas/eta-engine",
    },
    technologies: [
      "python",
      "pytorch",
      "lightgbm",
      "pandas",
      "mlflow",
      "docker",
      "hugging face hub",
    ],
    features: [
      {
        title: "3-model ensemble",
        description:
          "neural net + lightgbm + ft-transformer with complementary strengths. each model has a different inductive bias — embeddings vs tree splits vs self-attention. ensemble reduced mae from 261s to 253s.",
      },
      {
        title: "ft-transformer from scratch",
        description:
          "feature tokenizer transformer (gorishniy et al., neurips 2021). each feature projected into a 128-dim token, [cls] token aggregates via 3-layer self-attention. captures cross-feature interactions the mlp misses.",
      },
      {
        title: "learned zone embeddings",
        description:
          "50-dim embeddings for 266 zones learn spatial relationships purely from trip patterns. no external geography needed — model is transferable to any city with zone ids.",
      },
      {
        title: "bayesian shrinkage for sparse pairs",
        description:
          "handles rare and unseen zone pairs gracefully. shrinkage prior smooths toward pickup-zone mean; fallback hierarchy prevents cold-start failures.",
      },
      {
        title: "diagnostic-driven tuning",
        description:
          "deep diagnostics (parameter health, rare-pair analysis, regularization checks) revealed rare-pair bias as the true bottleneck. prevented wasted experiments on architecture changes.",
      },
      {
        title: "onnx runtime inference",
        description:
          "ft-transformer compressed from 406k to 169k params. onnx runtime inference from 11ms to 4ms on cpu.",
      },
    ],
    workflow: [
      "download and clean 37m taxi trips (2023), split temporally into train/dev",
      "compute zone-pair statistics with bayesian shrinkage across 6 traffic regimes",
      "train neural net (37m rows, huber loss), lightgbm (10m rows, mae), ft-transformer (10m rows, l1)",
      "optimize ensemble weights via grid search on full 1.23m dev set",
      "evaluate on held-out dev set, pick best checkpoint by mae (not training loss)",
    ],
  },
  {
    id: 3,
    name: "autonomous trader agent",
    date: "march, 2026",
    collabs: [],
    type: "ml/quant",
    featured: true,
    description:
      "autonomous trading system for indian equity markets using cross-sectional reversal scoring on nifty stocks. backtested 8.6% cagr with 60% win rate over 5.4 years.",
    contentSections: [
      {
        title: "the strategy",
        items: [
          "cross-sectional reversal — ranks nifty stocks by magnitude of decline over a 5-21 day lookback, buys the most oversold, holds for 5 trading days",
          "the edge is behavioral: panic selling pushes stocks below fair value, creating a mean-reversion opportunity that algorithms can't easily arbitrage away",
          "information coefficient: +0.020 (large-cap), +0.025 (midcap) — a small but consistent edge compounded over thousands of trades",
        ],
      },
      {
        title: "research journey",
        items: [
          "tested 6 strategies systematically before finding the edge",
          "5 failed: intraday ml prediction, breakout detection, 5-min mean reversion, 30-min trend following, cross-sectional ml — indian large-cap stocks are too efficient at intraday resolution",
          "daily reversal was the only signal that survived — driven by human psychology, not technical patterns",
          "evolved through 4 versions of allocation logic, each improving capital efficiency — the underlying signal never changed",
        ],
      },
      {
        title: "how it works",
        items: [
          "3-state regime classifier (bull/neutral/weak) using nifty vs 50-dma, momentum, and market breadth with a 2-day persistence filter",
          "adaptive confidence scoring: continuous 0-1 score combining ic, rolling win rate, momentum, and breadth for smooth capital allocation",
          "risk controls: regime-based exposure gates, soft drawdown dampening, recovery boost, kill switches on declining win rates or negative ic, panic filters",
          "a/b pipeline testing with independent scan intervals, capital pools, and paper broker instances for isolated comparison",
        ],
      },
      {
        title: "results",
        items: [
          "backtested over 5.4 years (oct 2020 – jan 2025): 8.6% cagr, 42% total return, 60% win rate",
          "survived the 2025-26 bear market with 6.5% cagr and 9-16% max drawdown",
          "large-cap returns: +38% | midcap returns: +108% (2.8x higher)",
          "~52% average capital deployment — the rest held as a protective cash buffer",
        ],
      },
    ],
    links: {
      github: "https://github.com/sarthakbiswas97/trader",
      demo: "https://trader.sarthakb.xyz",
    },
    technologies: [
      "python",
      "fastapi",
      "postgresql",
      "docker",
      "github actions",
      "zerodha kite connect",
    ],
    features: [
      {
        title: "cross-sectional reversal scoring",
        description:
          "ranks nifty stocks by decline magnitude. information coefficient: +0.020 (large-cap), +0.025 (midcap). exploits behavioral overreaction — a structural edge driven by psychology, not patterns algorithms can arbitrage away.",
      },
      {
        title: "3-state regime classifier",
        description:
          "classifies market as bull (65-85% exposure), neutral (50-75%), or weak (8-40%) using nifty vs 50-dma, momentum, and breadth. 2-day persistence filter prevents whipsawing.",
      },
      {
        title: "adaptive confidence scoring",
        description:
          "continuous 0-1 scoring combining information coefficient, rolling win rate, momentum, and market breadth. replaces hard thresholds for smoother capital allocation.",
      },
      {
        title: "a/b pipeline testing",
        description:
          "two independent pipelines with separate scan intervals and capital pools. each pipeline runs its own paper broker instance for isolated comparison.",
      },
      {
        title: "risk management layers",
        description:
          "regime-based exposure gates, soft drawdown dampening (gentle in bull, aggressive in weak), recovery boost when signal improves during drawdown recovery, and kill switches that pause trading on declining win rates or negative ic.",
      },
      {
        title: "research-driven development",
        description:
          "tested 6 strategies systematically before finding the edge. 5 failed (ml prediction, breakouts, intraday mean reversion, trend following, cross-sectional ml). every version improvement came from better capital allocation — the signal never changed.",
      },
    ],
    workflow: [
      "regime classifier evaluates market conditions (bull/neutral/weak)",
      "confidence scorer computes allocation weight from ic, win rate, momentum, breadth",
      "reversal scanner ranks stocks by decline magnitude across lookback windows",
      "risk guardian validates exposure limits, drawdown gates, and kill switches",
      "trade executor places orders via zerodha kite connect (cnc for swing holding)",
    ],
  },
  {
    id: 5,
    name: "rag system",
    date: "may, 2026",
    collabs: [],
    type: "ml/nlp",
    featured: true,
    description:
      "production rag system with zero-hallucination verification pipeline. nli entailment checking, hybrid search (vector + bm25 + cross-encoder reranking), multi-tenant architecture, and abstention decider.",
    contentSections: [
      {
        title: "verification pipeline",
        items: [
          "nli entailment checking using deberta v3 — verifies every answer is logically supported by source documents before returning to user",
          "citation validation ensures each cited passage actually supports the claim it's attached to",
          "multi-signal abstention decider with 6 detection signals — system refuses to answer rather than hallucinate",
          "faithfulness threshold at 0.7, citation support threshold at 0.5 — tunable per deployment",
        ],
      },
      {
        title: "hybrid search architecture",
        items: [
          "vector search (bge-small-en-v1.5 embeddings) for semantic similarity",
          "bm25 keyword search for exact term matching",
          "reciprocal rank fusion combines both retrieval methods",
          "cross-encoder reranking (ms-marco-minilm-l-6-v2) refines top candidates",
        ],
      },
      {
        title: "multi-tenant system",
        items: [
          "per-tenant document isolation with database-backed tenancy",
          "tenant authentication and authorization via api keys",
          "admin api for tenant management, document ingestion, and usage tracking",
          "async background job processing with redis for document ingestion status tracking",
        ],
      },
      {
        title: "evaluation framework",
        items: [
          "offline evaluation metrics: faithfulness, context utilization, citation precision",
          "cli evaluation runner with configurable thresholds",
          "35+ integration tests covering retrieval, verification, and end-to-end query flows",
          "prometheus metrics endpoint and structured logging for production observability",
        ],
      },
    ],
    links: {
      github: "https://github.com/sarthakbiswas97/rag-system",
    },
    technologies: [
      "fastapi",
      "qdrant",
      "redis",
      "openai",
      "sentence-transformers",
      "deberta",
      "docker",
      "prometheus",
    ],
    features: [
      {
        title: "zero-hallucination verification",
        description:
          "nli entailment checking verifies every answer against source documents. the system prefers abstention over hallucination — refuses uncertain answers rather than guessing.",
      },
      {
        title: "hybrid retrieval + reranking",
        description:
          "vector search + bm25 keyword search combined via reciprocal rank fusion, then refined by cross-encoder reranking. captures both semantic similarity and exact term matches.",
      },
      {
        title: "abstention decider",
        description:
          "6 detection signals determine whether the system should answer or refuse. prevents confident-sounding but unsupported responses — the core failure mode of naive rag.",
      },
      {
        title: "conversational context",
        description:
          "redis-backed session store with query rewriting using chat history. supports multi-turn conversations with context-aware retrieval.",
      },
      {
        title: "multi-format ingestion",
        description:
          "supports pdf, txt, docx, pptx via pymupdf. configurable chunking (512 chars with 64 overlap), content deduplication via hashing, async background processing with status tracking.",
      },
      {
        title: "production observability",
        description:
          "structured logging with context, prometheus metrics endpoint, per-request timing instrumentation, and health checks for api, qdrant, and database.",
      },
    ],
    workflow: [
      "documents ingested via api — parsed, chunked, deduplicated, embedded, stored in qdrant",
      "query arrives — rewritten with conversation history if multi-turn",
      "hybrid retrieval: vector search + bm25, fused via reciprocal rank fusion",
      "cross-encoder reranks top candidates for precision",
      "llm generates answer grounded in retrieved context with citations",
      "verification pipeline checks entailment, validates citations, decides whether to return or abstain",
    ],
  },
];
